### ISSUE TITLE
Dependency conflicts with other plugins ?

### ISSUE THREAD

**Issue by MikeBateman** [kraihn/cordova-plugin-tag-manager#12]
Hi, 

i am trying to use two plugins in the same app:

(to collect the IDFA)
cordova plugin add https://github.com/appfeel/analytics-google-adid.git
(to use GTM)
cordova plugin add https://github.com/kraihn/cordova-plugin-tag-manager.git

but when i try to build i get:

UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/analytics/internal/Command$1;

After looking into this a little bit i think that this plugin includes libraries that should be dependencies? I think it might be something to do with libGoogleAnalyticsServices.jar??
Sorry if i have got this wrong but i can't get the two plugins to work well together,

Any ideas?
MB

**Comment by kraihn** [comment]
Hi @MikeBateman, because the jar file is use is a straight lib (downloaded from Google), and not another Cordova plugin, I don't believe that marking this as a dependency in the plugin is possible. However, I may be mistaken. All the other resources I've found include libs as part of the repo/plugin.

As for your issue, I'm not sure how I can help. The error you called out is being thrown from the lib in the other plugin, and not being thrown from the one in my project. They have different package names, so I don't see the possibility for conflict.

**Comment by MikeBateman** [comment]
Thanks for the response, I'm new to Cordova and working out how the plugin system works, I'll have look at the other plugin and see how that's using the Google lib

**Comment by SMJ93** [comment]
Any solution to this?

I am getting the same issue when installing Google Tag Manager after having Google Analytics previously installed.

**Comment by kraihn** [comment]
You need to uninstall and remove all previous Google Analytics files and dependencies.

**Comment by rathoremegha** [comment]
I am already using google play services library in my application

when I add this plugin libGoogleAnalyticsServices.jar gets added in my project automatically 

now both google play services library and libGoogleAnalyticsServices library have Command class in same package but when i decompiled the jars Command classes in both libs have different code(maybe cz of version differences) because of which i am getting this error in my android project gradle build

Error:Execution failed for task ':transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/android/gms/analytics/internal/Command.class
